# Generated by Django 5.0.6 on 2026-08-05 16:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0004_plantillas_por_rubro'),
        ('servicios', '0002_registroservicio'),
        ('tenants', '0001_initial'),
        ('usuarios', '0007_cargo_puede_editar_comisiones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=10)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('abierta_en', models.DateTimeField(auto_now_add=True)),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('nota_cierre', models.TextField(blank=True)),
                ('abierta_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas_abiertas', to='usuarios.miembronegocio')),
                ('cerrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cajas_cerradas', to='usuarios.miembronegocio')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='negocios.negocio')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-abierta_en'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('bre_b', 'Bre-B'), ('otro', 'Otro')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('concepto', models.CharField(max_length=200)),
                ('monto_comision', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='caja.caja')),
                ('empleado_comision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comisiones', to='usuarios.miembronegocio')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja', to='negocios.negocio')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_registrados', to='usuarios.miembronegocio')),
                ('registro_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to='servicios.registroservicio')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acciones_caja', to='usuarios.miembronegocio')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_caja', to='negocios.negocio')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'registros de auditoría',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='caja',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'abierta')), fields=('negocio',), name='una_caja_abierta_por_negocio'),
        ),
        migrations.AddConstraint(
            model_name='movimientocaja',
            constraint=models.UniqueConstraint(condition=models.Q(('registro_servicio__isnull', False)), fields=('registro_servicio',), name='un_movimiento_por_registro_servicio'),
        ),
    ]
