# Generated by Django 5.0.6 on 2026-08-07 23:41

import apps.caja.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_cita_estado'),
        ('caja', '0001_initial'),
        ('negocios', '0004_plantillas_por_rubro'),
        ('servicios', '0002_registroservicio'),
        ('tenants', '0001_initial'),
        ('usuarios', '0008_remove_cargo_puede_aprobar_servicios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComisionDevengada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'comisiones devengadas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('bre_b', 'Bre-B'), ('otro', 'Otro')], max_length=12)),
                ('motivo', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('bre_b', 'Bre-B'), ('otro', 'Otro')], max_length=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=150)),
                ('telefono_cliente', models.CharField(blank=True, max_length=30)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de cobro'), ('parcial', 'Pagada parcialmente'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='pendiente', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('evidencia', models.ImageField(blank=True, upload_to=apps.caja.models.ruta_evidencia)),
                ('anulada_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='VentaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='movimientocaja',
            name='un_movimiento_por_registro_servicio',
        ),
        migrations.RemoveField(
            model_name='movimientocaja',
            name='empleado_comision',
        ),
        migrations.RemoveField(
            model_name='movimientocaja',
            name='monto_comision',
        ),
        migrations.RemoveField(
            model_name='movimientocaja',
            name='registro_servicio',
        ),
        migrations.AddField(
            model_name='caja',
            name='diferencia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='efectivo_contado − efectivo_esperado. Negativo es faltante.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='efectivo_contado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lo que la persona contó de verdad en el cajón.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='efectivo_esperado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='saldo_inicial + ingresos en efectivo − egresos en efectivo − devoluciones en efectivo, al momento del cierre.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='categoria',
            field=models.CharField(blank=True, choices=[('insumos', 'Insumos'), ('servicios_publicos', 'Servicios públicos'), ('arriendo', 'Arriendo'), ('transporte', 'Transporte'), ('mantenimiento', 'Mantenimiento'), ('nomina', 'Nómina'), ('comisiones', 'Comisiones'), ('otros', 'Otros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='caja',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Efectivo con el que arranca el cajón (la base).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='caja.caja'),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('bre_b', 'Bre-B'), ('otro', 'Otro')], max_length=12),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='monto',
            field=models.DecimalField(decimal_places=2, help_text='Siempre positivo. El signo lo da `tipo`, no el monto.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso'), ('devolucion', 'Devolución')], max_length=12),
        ),
        migrations.AddField(
            model_name='comisiondevengada',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comisiones', to='usuarios.miembronegocio'),
        ),
        migrations.AddField(
            model_name='comisiondevengada',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='negocios.negocio'),
        ),
        migrations.AddField(
            model_name='comisiondevengada',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='movimiento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='devolucion', to='caja.movimientocaja'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='negocios.negocio'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_registradas', to='usuarios.miembronegocio'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='pago',
            name='movimiento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='caja.movimientocaja'),
        ),
        migrations.AddField(
            model_name='pago',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='negocios.negocio'),
        ),
        migrations.AddField(
            model_name='pago',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to='usuarios.miembronegocio'),
        ),
        migrations.AddField(
            model_name='pago',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='venta',
            name='anulada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_anuladas', to='usuarios.miembronegocio'),
        ),
        migrations.AddField(
            model_name='venta',
            name='cita',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='venta', to='agenda.cita'),
        ),
        migrations.AddField(
            model_name='venta',
            name='creada_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_creadas', to='usuarios.miembronegocio'),
        ),
        migrations.AddField(
            model_name='venta',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='negocios.negocio'),
        ),
        migrations.AddField(
            model_name='venta',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='pago',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='caja.venta'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='caja.venta'),
        ),
        migrations.AddField(
            model_name='comisiondevengada',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='caja.venta'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='caja.venta'),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_venta', to='usuarios.miembronegocio'),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_venta', to='negocios.negocio'),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_venta', to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='caja.venta'),
        ),
        migrations.AddField(
            model_name='comisiondevengada',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comision', to='caja.ventaitem'),
        ),
    ]
