# Generated by Django 5.0.6 on 2026-07-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembronegocio',
            name='especialidad',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
