# Generated by Django 5.0.6 on 2026-07-26 23:14

from django.db import migrations, models


def derivar_de_gestionar_agenda(apps, schema_editor):
    """`puede_gestionar_agenda` se partió en tres capacidades.

    Quien administraba la agenda hacía las tres cosas —configurar
    horarios, operar citas y ver las de todo el negocio—, así que
    conserva las tres y para esas membresías no cambia nada.

    Para el resto **sí cambia**, y es el objetivo del cambio: un empleado
    sin `puede_gestionar_agenda` pasa a ver solo sus propias citas, no las
    de todo el negocio con nombre y teléfono del cliente incluidos.
    """
    MiembroNegocio = apps.get_model("usuarios", "MiembroNegocio")
    MiembroNegocio.objects.filter(puede_gestionar_agenda=True).update(
        puede_configurar_horarios=True, puede_ver_agenda_completa=True
    )


def revertir(apps, schema_editor):
    """Nada que deshacer: al quitar las columnas se pierden los valores."""


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_miembronegocio_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembronegocio',
            name='puede_configurar_horarios',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='miembronegocio',
            name='puede_ver_agenda_completa',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(derivar_de_gestionar_agenda, revertir),
    ]
