# Generated by Django 5.0.6 on 2026-07-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_cargos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='puede_editar_negocio',
            field=models.BooleanField(default=False),
        ),
    ]
