# Generated by Django 5.0.6 on 2026-07-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_cargo_puede_editar_negocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='puede_aprobar_servicios',
            field=models.BooleanField(default=False),
        ),
    ]
