# Generated by Django 5.0.6 on 2026-08-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_cargo_puede_aprobar_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='puede_editar_comisiones',
            field=models.BooleanField(default=False),
        ),
    ]
