# Generated by Django 5.0.6 on 2026-08-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_cargo_puede_editar_comisiones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='puede_aprobar_servicios',
        ),
        migrations.AddField(
            model_name='cargo',
            name='puede_anular_venta',
            field=models.BooleanField(default=False),
        ),
    ]
