# Generated by Django 5.0.6 on 2026-08-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_horarionegocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('en_atencion', 'En atención'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_show', 'No asistió')], default='agendada', max_length=20),
        ),
    ]
