/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/agenda/citas/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Agenda: crear y consultar citas, y transicionar su estado.
         *
         *     Crear requiere `puede_gestionar_agenda`. `empleado` es opcional al
         *     crear: si se omite, el servicio de agenda asigna automáticamente el
         *     primer empleado disponible ("cualquiera disponible").
         *
         *     Transicionar (`confirmar`/`completar`/`cancelar`) lo puede hacer quien
         *     tenga `puede_gestionar_agenda` sobre **cualquier** cita del negocio, o
         *     cualquier miembro sobre **sus propias** citas: marcar que el cliente
         *     llegó no es un acto administrativo, es el empleado haciendo su
         *     trabajo. Ver `CONTRATO.md` sección 5.6.
         */
        get: operations["agenda_citas_list"];
        put?: never;
        /**
         * @description Agenda: crear y consultar citas, y transicionar su estado.
         *
         *     Crear requiere `puede_gestionar_agenda`. `empleado` es opcional al
         *     crear: si se omite, el servicio de agenda asigna automáticamente el
         *     primer empleado disponible ("cualquiera disponible").
         *
         *     Transicionar (`confirmar`/`completar`/`cancelar`) lo puede hacer quien
         *     tenga `puede_gestionar_agenda` sobre **cualquier** cita del negocio, o
         *     cualquier miembro sobre **sus propias** citas: marcar que el cliente
         *     llegó no es un acto administrativo, es el empleado haciendo su
         *     trabajo. Ver `CONTRATO.md` sección 5.6.
         */
        post: operations["agenda_citas_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agenda/citas/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Agenda: crear y consultar citas, y transicionar su estado.
         *
         *     Crear requiere `puede_gestionar_agenda`. `empleado` es opcional al
         *     crear: si se omite, el servicio de agenda asigna automáticamente el
         *     primer empleado disponible ("cualquiera disponible").
         *
         *     Transicionar (`confirmar`/`completar`/`cancelar`) lo puede hacer quien
         *     tenga `puede_gestionar_agenda` sobre **cualquier** cita del negocio, o
         *     cualquier miembro sobre **sus propias** citas: marcar que el cliente
         *     llegó no es un acto administrativo, es el empleado haciendo su
         *     trabajo. Ver `CONTRATO.md` sección 5.6.
         */
        get: operations["agenda_citas_retrieve"];
        /**
         * @description Agenda: crear y consultar citas, y transicionar su estado.
         *
         *     Crear requiere `puede_gestionar_agenda`. `empleado` es opcional al
         *     crear: si se omite, el servicio de agenda asigna automáticamente el
         *     primer empleado disponible ("cualquiera disponible").
         *
         *     Transicionar (`confirmar`/`completar`/`cancelar`) lo puede hacer quien
         *     tenga `puede_gestionar_agenda` sobre **cualquier** cita del negocio, o
         *     cualquier miembro sobre **sus propias** citas: marcar que el cliente
         *     llegó no es un acto administrativo, es el empleado haciendo su
         *     trabajo. Ver `CONTRATO.md` sección 5.6.
         */
        put: operations["agenda_citas_update"];
        post?: never;
        /**
         * @description Agenda: crear y consultar citas, y transicionar su estado.
         *
         *     Crear requiere `puede_gestionar_agenda`. `empleado` es opcional al
         *     crear: si se omite, el servicio de agenda asigna automáticamente el
         *     primer empleado disponible ("cualquiera disponible").
         *
         *     Transicionar (`confirmar`/`completar`/`cancelar`) lo puede hacer quien
         *     tenga `puede_gestionar_agenda` sobre **cualquier** cita del negocio, o
         *     cualquier miembro sobre **sus propias** citas: marcar que el cliente
         *     llegó no es un acto administrativo, es el empleado haciendo su
         *     trabajo. Ver `CONTRATO.md` sección 5.6.
         */
        delete: operations["agenda_citas_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Agenda: crear y consultar citas, y transicionar su estado.
         *
         *     Crear requiere `puede_gestionar_agenda`. `empleado` es opcional al
         *     crear: si se omite, el servicio de agenda asigna automáticamente el
         *     primer empleado disponible ("cualquiera disponible").
         *
         *     Transicionar (`confirmar`/`completar`/`cancelar`) lo puede hacer quien
         *     tenga `puede_gestionar_agenda` sobre **cualquier** cita del negocio, o
         *     cualquier miembro sobre **sus propias** citas: marcar que el cliente
         *     llegó no es un acto administrativo, es el empleado haciendo su
         *     trabajo. Ver `CONTRATO.md` sección 5.6.
         */
        patch: operations["agenda_citas_partial_update"];
        trace?: never;
    };
    "/api/agenda/citas/{id}/cancelar/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Agenda: crear y consultar citas, y transicionar su estado.
         *
         *     Crear requiere `puede_gestionar_agenda`. `empleado` es opcional al
         *     crear: si se omite, el servicio de agenda asigna automáticamente el
         *     primer empleado disponible ("cualquiera disponible").
         *
         *     Transicionar (`confirmar`/`completar`/`cancelar`) lo puede hacer quien
         *     tenga `puede_gestionar_agenda` sobre **cualquier** cita del negocio, o
         *     cualquier miembro sobre **sus propias** citas: marcar que el cliente
         *     llegó no es un acto administrativo, es el empleado haciendo su
         *     trabajo. Ver `CONTRATO.md` sección 5.6.
         */
        post: operations["agenda_citas_cancelar_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agenda/citas/{id}/completar/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Agenda: crear y consultar citas, y transicionar su estado.
         *
         *     Crear requiere `puede_gestionar_agenda`. `empleado` es opcional al
         *     crear: si se omite, el servicio de agenda asigna automáticamente el
         *     primer empleado disponible ("cualquiera disponible").
         *
         *     Transicionar (`confirmar`/`completar`/`cancelar`) lo puede hacer quien
         *     tenga `puede_gestionar_agenda` sobre **cualquier** cita del negocio, o
         *     cualquier miembro sobre **sus propias** citas: marcar que el cliente
         *     llegó no es un acto administrativo, es el empleado haciendo su
         *     trabajo. Ver `CONTRATO.md` sección 5.6.
         */
        post: operations["agenda_citas_completar_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agenda/citas/{id}/confirmar/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Agenda: crear y consultar citas, y transicionar su estado.
         *
         *     Crear requiere `puede_gestionar_agenda`. `empleado` es opcional al
         *     crear: si se omite, el servicio de agenda asigna automáticamente el
         *     primer empleado disponible ("cualquiera disponible").
         *
         *     Transicionar (`confirmar`/`completar`/`cancelar`) lo puede hacer quien
         *     tenga `puede_gestionar_agenda` sobre **cualquier** cita del negocio, o
         *     cualquier miembro sobre **sus propias** citas: marcar que el cliente
         *     llegó no es un acto administrativo, es el empleado haciendo su
         *     trabajo. Ver `CONTRATO.md` sección 5.6.
         */
        post: operations["agenda_citas_confirmar_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agenda/horarios/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Horario semanal recurrente de los empleados del negocio. */
        get: operations["agenda_horarios_list"];
        put?: never;
        /** @description Horario semanal recurrente de los empleados del negocio. */
        post: operations["agenda_horarios_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agenda/horarios/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Horario semanal recurrente de los empleados del negocio. */
        get: operations["agenda_horarios_retrieve"];
        /** @description Horario semanal recurrente de los empleados del negocio. */
        put: operations["agenda_horarios_update"];
        post?: never;
        /** @description Horario semanal recurrente de los empleados del negocio. */
        delete: operations["agenda_horarios_destroy"];
        options?: never;
        head?: never;
        /** @description Horario semanal recurrente de los empleados del negocio. */
        patch: operations["agenda_horarios_partial_update"];
        trace?: never;
    };
    "/api/agenda/horarios/semana/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * @description Reemplaza de una vez el horario semanal completo de un empleado, en una sola transacción.
         *
         *     Semántica de **reemplazo**: las franjas enviadas pasan a ser el horario completo del empleado; lo que no venga en la lista se borra. Enviar `franjas: []` lo deja sin disponibilidad.
         *
         *     Existe para que el frontend no tenga que emitir un DELETE/POST por franja al editar la semana, que no era atómico.
         */
        put: operations["agenda_horarios_semana_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/negocios/empleados/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Lista o agrega empleados del negocio del usuario autenticado.
         *
         *     Endpoint de **gestión**: expone email y capacidades de cada miembro,
         *     así que exige `puede_gestionar_empleados` también para listar, no
         *     solo para crear. Quien solo necesita saber quiénes son sus
         *     compañeros (la agenda) usa `GET /api/negocios/equipo/`, que
         *     devuelve una vista mínima sin datos personales.
         *
         *     El queryset se filtra siempre por el negocio de la membresía activa
         *     del solicitante: nunca se exponen empleados de otro tenant.
         */
        get: operations["negocios_empleados_list"];
        put?: never;
        /**
         * @description Lista o agrega empleados del negocio del usuario autenticado.
         *
         *     Endpoint de **gestión**: expone email y capacidades de cada miembro,
         *     así que exige `puede_gestionar_empleados` también para listar, no
         *     solo para crear. Quien solo necesita saber quiénes son sus
         *     compañeros (la agenda) usa `GET /api/negocios/equipo/`, que
         *     devuelve una vista mínima sin datos personales.
         *
         *     El queryset se filtra siempre por el negocio de la membresía activa
         *     del solicitante: nunca se exponen empleados de otro tenant.
         */
        post: operations["negocios_empleados_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/negocios/empleados/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Detalle y edición de un empleado puntual del negocio.
         *
         *     Tanto ver como editar requieren `puede_gestionar_empleados`: el
         *     detalle incluye email y capacidades, que son datos de gestión. Nunca
         *     expone empleados de otro tenant: el queryset ya viene acotado al
         *     negocio de la membresía del solicitante.
         */
        get: operations["negocios_empleados_retrieve"];
        /**
         * @description Detalle y edición de un empleado puntual del negocio.
         *
         *     Tanto ver como editar requieren `puede_gestionar_empleados`: el
         *     detalle incluye email y capacidades, que son datos de gestión. Nunca
         *     expone empleados de otro tenant: el queryset ya viene acotado al
         *     negocio de la membresía del solicitante.
         */
        put: operations["negocios_empleados_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description Detalle y edición de un empleado puntual del negocio.
         *
         *     Tanto ver como editar requieren `puede_gestionar_empleados`: el
         *     detalle incluye email y capacidades, que son datos de gestión. Nunca
         *     expone empleados de otro tenant: el queryset ya viene acotado al
         *     negocio de la membresía del solicitante.
         */
        patch: operations["negocios_empleados_partial_update"];
        trace?: never;
    };
    "/api/negocios/equipo/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Directorio mínimo del equipo, para cualquier miembro del negocio.
         *
         *     Devuelve solo `id`, `nombre`, `especialidad` y `activo`: lo que la
         *     agenda necesita para filtrar el calendario, ofrecer "cualquiera
         *     disponible" y cargar horarios, sin exponer email ni capacidades.
         *
         *     Separado de `/empleados/` a propósito: así cada endpoint tiene una
         *     forma honesta en el schema, en vez de un mismo endpoint que devuelve
         *     más o menos campos según quién pregunte.
         */
        get: operations["negocios_equipo_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/negocios/mi-membresia/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Quién soy, en qué negocio y qué puedo hacer.
         *
         *     Pensado para que el frontend lo llame justo después de loguearse
         *     (o al recuperar sesión desde tokens guardados) y resuelva de una
         *     sola vez sus propias capacidades + los datos del negocio, sin
         *     tener que listar empleados y buscarse a sí mismo por email.
         */
        get: operations["negocios_mi_membresia_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/negocios/registro/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Alta de un negocio nuevo, con su dueño (todas las capacidades) y,
         *     opcionalmente, empleados adicionales desde el mismo registro.
         */
        post: operations["negocios_registro_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servicios/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description CRUD de servicios del negocio del usuario autenticado.
         *
         *     Leer requiere solo pertenecer al negocio; crear/editar/borrar
         *     requiere la capacidad `puede_editar_precios`, porque un servicio
         *     define precio y comisión.
         */
        get: operations["servicios_list"];
        put?: never;
        /**
         * @description CRUD de servicios del negocio del usuario autenticado.
         *
         *     Leer requiere solo pertenecer al negocio; crear/editar/borrar
         *     requiere la capacidad `puede_editar_precios`, porque un servicio
         *     define precio y comisión.
         */
        post: operations["servicios_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servicios/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description CRUD de servicios del negocio del usuario autenticado.
         *
         *     Leer requiere solo pertenecer al negocio; crear/editar/borrar
         *     requiere la capacidad `puede_editar_precios`, porque un servicio
         *     define precio y comisión.
         */
        get: operations["servicios_retrieve"];
        /**
         * @description CRUD de servicios del negocio del usuario autenticado.
         *
         *     Leer requiere solo pertenecer al negocio; crear/editar/borrar
         *     requiere la capacidad `puede_editar_precios`, porque un servicio
         *     define precio y comisión.
         */
        put: operations["servicios_update"];
        post?: never;
        /**
         * @description CRUD de servicios del negocio del usuario autenticado.
         *
         *     Leer requiere solo pertenecer al negocio; crear/editar/borrar
         *     requiere la capacidad `puede_editar_precios`, porque un servicio
         *     define precio y comisión.
         */
        delete: operations["servicios_destroy"];
        options?: never;
        head?: never;
        /**
         * @description CRUD de servicios del negocio del usuario autenticado.
         *
         *     Leer requiere solo pertenecer al negocio; crear/editar/borrar
         *     requiere la capacidad `puede_editar_precios`, porque un servicio
         *     define precio y comisión.
         */
        patch: operations["servicios_partial_update"];
        trace?: never;
    };
    "/api/servicios/lote/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Crea varios servicios en una sola transacción: entran todos o ninguno.
         *
         *     Pensado para el alta desde catálogo del frontend, que antes emitía un POST por servicio y podía quedar a medias si fallaba la red.
         */
        post: operations["servicios_lote_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Cita: {
            readonly id: number;
            servicio: number;
            readonly servicio_nombre: string;
            empleado: number;
            readonly empleado_nombre: string;
            /** Format: date-time */
            fecha_hora_inicio: string;
            /** Format: date-time */
            readonly fecha_hora_fin: string;
            readonly estado: components["schemas"]["EstadoEnum"];
            nombre_cliente: string;
            telefono_cliente?: string;
            notas?: string;
        };
        /**
         * @description Entrada para agendar una cita. `empleado` es opcional: si se
         *     omite, se asigna automáticamente el primer empleado disponible.
         */
        CitaCreate: {
            servicio: number;
            empleado?: number | null;
            /** Format: date-time */
            fecha_hora_inicio: string;
            nombre_cliente: string;
            /** @default  */
            telefono_cliente: string;
            /** @default  */
            notas: string;
        };
        /**
         * @description * `0` - Lunes
         *     * `1` - Martes
         *     * `2` - Miércoles
         *     * `3` - Jueves
         *     * `4` - Viernes
         *     * `5` - Sábado
         *     * `6` - Domingo
         * @enum {integer}
         */
        DiaSemanaEnum: 0 | 1 | 2 | 3 | 4 | 5 | 6;
        /** @description Empleado adicional dado de alta junto con el registro del negocio. */
        EmpleadoAlta: {
            /** Format: email */
            email: string;
            nombre: string;
            password: string;
            /** @default  */
            especialidad: string;
            /** @default false */
            puede_cobrar: boolean;
            /** @default false */
            puede_ver_reportes: boolean;
            /** @default false */
            puede_editar_precios: boolean;
            /** @default false */
            puede_gestionar_empleados: boolean;
            /** @default false */
            puede_gestionar_agenda: boolean;
        };
        /**
         * @description * `agendada` - Agendada
         *     * `confirmada` - Confirmada
         *     * `completada` - Completada
         *     * `cancelada` - Cancelada
         * @enum {string}
         */
        EstadoEnum: "agendada" | "confirmada" | "completada" | "cancelada";
        /**
         * @description Una franja suelta dentro de la semana. Sin `miembro`: lo define el
         *     contenedor, para no repetirlo en cada elemento de la lista.
         */
        FranjaHorario: {
            dia_semana: components["schemas"]["DiaSemanaEnum"];
            /** Format: time */
            hora_inicio: string;
            /** Format: time */
            hora_fin: string;
        };
        /**
         * @description Entrada de `PUT /api/agenda/horarios/semana/`.
         *
         *     Semántica de reemplazo: la lista es el horario completo del empleado,
         *     no un agregado. Mandar `franjas: []` lo deja sin disponibilidad.
         */
        HorarioSemanal: {
            miembro: number;
            franjas: components["schemas"]["FranjaHorario"][];
        };
        HorarioTrabajo: {
            readonly id: number;
            miembro: number;
            dia_semana: components["schemas"]["DiaSemanaEnum"];
            /** Format: time */
            hora_inicio: string;
            /** Format: time */
            hora_fin: string;
        };
        /**
         * @description Forma de la respuesta de GET /api/negocios/mi-membresia/.
         *
         *     Pensado para que el frontend, justo después de loguearse, resuelva
         *     en un solo request "quién soy, en qué negocio y qué puedo hacer"
         *     sin tener que listar empleados y buscarse a sí mismo por email.
         */
        MiMembresia: {
            readonly id: number;
            /** Format: email */
            readonly email: string;
            readonly nombre: string;
            readonly especialidad: string;
            readonly negocio: components["schemas"]["Negocio"];
            readonly puede_cobrar: boolean;
            readonly puede_ver_reportes: boolean;
            readonly puede_editar_precios: boolean;
            readonly puede_gestionar_empleados: boolean;
            readonly puede_gestionar_agenda: boolean;
            readonly activo: boolean;
        };
        /**
         * @description Vista mínima de un compañero de trabajo, para quien NO gestiona
         *     el equipo.
         *
         *     Existe porque la agenda necesita listar empleados (filtrar el
         *     calendario, elegir a quién asignar una cita, cargar horarios), pero
         *     eso no justifica exponerle a cualquier miembro el email y la matriz
         *     de capacidades de todos sus compañeros — que es lo que hacía
         *     `MiembroNegocioSerializer` cuando se usaba para listar sin exigir
         *     `puede_gestionar_empleados`.
         *
         *     Deliberadamente sin `email` ni flags `puede_*`.
         */
        MiembroEquipo: {
            readonly id: number;
            readonly nombre: string;
            readonly especialidad: string;
            readonly activo: boolean;
        };
        MiembroNegocio: {
            readonly id: number;
            /** Format: email */
            readonly email: string;
            readonly nombre: string;
            especialidad?: string;
            puede_cobrar?: boolean;
            puede_ver_reportes?: boolean;
            puede_editar_precios?: boolean;
            puede_gestionar_empleados?: boolean;
            puede_gestionar_agenda?: boolean;
            activo?: boolean;
        };
        Negocio: {
            readonly id: number;
            readonly nombre: string;
            readonly slug: string;
            readonly ciudad: string;
            readonly direccion: string;
            readonly telefono: string;
            readonly activo: boolean;
        };
        PatchedCita: {
            readonly id?: number;
            servicio?: number;
            readonly servicio_nombre?: string;
            empleado?: number;
            readonly empleado_nombre?: string;
            /** Format: date-time */
            fecha_hora_inicio?: string;
            /** Format: date-time */
            readonly fecha_hora_fin?: string;
            readonly estado?: components["schemas"]["EstadoEnum"];
            nombre_cliente?: string;
            telefono_cliente?: string;
            notas?: string;
        };
        PatchedHorarioTrabajo: {
            readonly id?: number;
            miembro?: number;
            dia_semana?: components["schemas"]["DiaSemanaEnum"];
            /** Format: time */
            hora_inicio?: string;
            /** Format: time */
            hora_fin?: string;
        };
        PatchedMiembroNegocio: {
            readonly id?: number;
            /** Format: email */
            readonly email?: string;
            readonly nombre?: string;
            especialidad?: string;
            puede_cobrar?: boolean;
            puede_ver_reportes?: boolean;
            puede_editar_precios?: boolean;
            puede_gestionar_empleados?: boolean;
            puede_gestionar_agenda?: boolean;
            activo?: boolean;
        };
        PatchedServicio: {
            readonly id?: number;
            nombre?: string;
            descripcion?: string;
            categoria?: string;
            /** Format: decimal */
            precio?: string;
            duracion_minutos?: number;
            /** Format: decimal */
            porcentaje_comision?: string;
            activo?: boolean;
        };
        RegistroNegocio: {
            nombre_negocio: string;
            ciudad?: string;
            direccion?: string;
            telefono?: string;
            /** Format: email */
            email_dueno: string;
            nombre_dueno: string;
            password_dueno: string;
            empleados?: components["schemas"]["EmpleadoAlta"][];
        };
        /** @description Forma de la respuesta de POST /api/negocios/registro/. */
        RegistroNegocioRespuesta: {
            negocio: components["schemas"]["Negocio"];
            access: string;
            refresh: string;
        };
        Servicio: {
            readonly id: number;
            nombre: string;
            descripcion?: string;
            categoria?: string;
            /** Format: decimal */
            precio: string;
            duracion_minutos: number;
            /** Format: decimal */
            porcentaje_comision?: string;
            activo?: boolean;
        };
        /**
         * @description Entrada de `POST /api/servicios/lote/`.
         *
         *     Se creó como endpoint aparte en vez de aceptar una lista en el `POST`
         *     normal para no volver ambiguo el body de creación de a uno: el
         *     schema OpenAPI quedaría con un `oneOf` que el frontend tendría que
         *     desambiguar en cada llamada.
         */
        ServicioLote: {
            servicios: components["schemas"]["Servicio"][];
        };
        TokenObtainPair: {
            email: string;
            password: string;
            readonly access: string;
            readonly refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    agenda_citas_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cita"][];
                };
            };
        };
    };
    agenda_citas_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CitaCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["CitaCreate"];
                "multipart/form-data": components["schemas"]["CitaCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cita"];
                };
            };
        };
    };
    agenda_citas_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this cita. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cita"];
                };
            };
        };
    };
    agenda_citas_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this cita. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Cita"];
                "application/x-www-form-urlencoded": components["schemas"]["Cita"];
                "multipart/form-data": components["schemas"]["Cita"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cita"];
                };
            };
        };
    };
    agenda_citas_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this cita. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    agenda_citas_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this cita. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCita"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCita"];
                "multipart/form-data": components["schemas"]["PatchedCita"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cita"];
                };
            };
        };
    };
    agenda_citas_cancelar_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this cita. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cita"];
                };
            };
        };
    };
    agenda_citas_completar_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this cita. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cita"];
                };
            };
        };
    };
    agenda_citas_confirmar_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this cita. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cita"];
                };
            };
        };
    };
    agenda_horarios_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HorarioTrabajo"][];
                };
            };
        };
    };
    agenda_horarios_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HorarioTrabajo"];
                "application/x-www-form-urlencoded": components["schemas"]["HorarioTrabajo"];
                "multipart/form-data": components["schemas"]["HorarioTrabajo"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HorarioTrabajo"];
                };
            };
        };
    };
    agenda_horarios_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this horario trabajo. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HorarioTrabajo"];
                };
            };
        };
    };
    agenda_horarios_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this horario trabajo. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HorarioTrabajo"];
                "application/x-www-form-urlencoded": components["schemas"]["HorarioTrabajo"];
                "multipart/form-data": components["schemas"]["HorarioTrabajo"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HorarioTrabajo"];
                };
            };
        };
    };
    agenda_horarios_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this horario trabajo. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    agenda_horarios_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this horario trabajo. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedHorarioTrabajo"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedHorarioTrabajo"];
                "multipart/form-data": components["schemas"]["PatchedHorarioTrabajo"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HorarioTrabajo"];
                };
            };
        };
    };
    agenda_horarios_semana_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HorarioSemanal"];
                "application/x-www-form-urlencoded": components["schemas"]["HorarioSemanal"];
                "multipart/form-data": components["schemas"]["HorarioSemanal"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HorarioTrabajo"][];
                };
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
                "multipart/form-data": components["schemas"]["TokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    negocios_empleados_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MiembroNegocio"][];
                };
            };
        };
    };
    negocios_empleados_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmpleadoAlta"];
                "application/x-www-form-urlencoded": components["schemas"]["EmpleadoAlta"];
                "multipart/form-data": components["schemas"]["EmpleadoAlta"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MiembroNegocio"];
                };
            };
        };
    };
    negocios_empleados_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MiembroNegocio"];
                };
            };
        };
    };
    negocios_empleados_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MiembroNegocio"];
                "application/x-www-form-urlencoded": components["schemas"]["MiembroNegocio"];
                "multipart/form-data": components["schemas"]["MiembroNegocio"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MiembroNegocio"];
                };
            };
        };
    };
    negocios_empleados_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMiembroNegocio"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedMiembroNegocio"];
                "multipart/form-data": components["schemas"]["PatchedMiembroNegocio"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MiembroNegocio"];
                };
            };
        };
    };
    negocios_equipo_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MiembroEquipo"][];
                };
            };
        };
    };
    negocios_mi_membresia_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MiMembresia"];
                };
            };
        };
    };
    negocios_registro_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistroNegocio"];
                "application/x-www-form-urlencoded": components["schemas"]["RegistroNegocio"];
                "multipart/form-data": components["schemas"]["RegistroNegocio"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistroNegocioRespuesta"];
                };
            };
        };
    };
    servicios_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Servicio"][];
                };
            };
        };
    };
    servicios_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Servicio"];
                "application/x-www-form-urlencoded": components["schemas"]["Servicio"];
                "multipart/form-data": components["schemas"]["Servicio"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Servicio"];
                };
            };
        };
    };
    servicios_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this servicio. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Servicio"];
                };
            };
        };
    };
    servicios_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this servicio. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Servicio"];
                "application/x-www-form-urlencoded": components["schemas"]["Servicio"];
                "multipart/form-data": components["schemas"]["Servicio"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Servicio"];
                };
            };
        };
    };
    servicios_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this servicio. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    servicios_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this servicio. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedServicio"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedServicio"];
                "multipart/form-data": components["schemas"]["PatchedServicio"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Servicio"];
                };
            };
        };
    };
    servicios_lote_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServicioLote"];
                "application/x-www-form-urlencoded": components["schemas"]["ServicioLote"];
                "multipart/form-data": components["schemas"]["ServicioLote"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Servicio"][];
                };
            };
        };
    };
}
