/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/agenda/citas/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Agenda: crear y consultar citas, y transicionar su estado.
         *
         *     Crear requiere `puede_gestionar_agenda`. `empleado` es opcional al
         *     crear: si se omite, el servicio de agenda asigna automáticamente el
         *     primer empleado disponible ("cualquiera disponible").
         *
         *     Transicionar (`confirmar`/`completar`/`cancelar`) lo puede hacer quien
         *     tenga `puede_gestionar_agenda` sobre **cualquier** cita del negocio, o
         *     cualquier miembro sobre **sus propias** citas: marcar que el cliente
         *     llegó no es un acto administrativo, es el empleado haciendo su
         *     trabajo. Ver `CONTRATO.md` sección 5.6.
         *
         *     Listar devuelve solo las citas propias salvo que se tenga
         *     `puede_ver_agenda_completa`: cada cita trae nombre y teléfono del
         *     cliente, así que la agenda completa **es** la libreta de clientes del
         *     negocio (ver `CONTRATO.md` sección 5.8).
         */
        get: operations["agenda_citas_list"];
        put?: never;
        /**
         * @description Agenda: crear y consultar citas, y transicionar su estado.
         *
         *     Crear requiere `puede_gestionar_agenda`. `empleado` es opcional al
         *     crear: si se omite, el servicio de agenda asigna automáticamente el
         *     primer empleado disponible ("cualquiera disponible").
         *
         *     Transicionar (`confirmar`/`completar`/`cancelar`) lo puede hacer quien
         *     tenga `puede_gestionar_agenda` sobre **cualquier** cita del negocio, o
         *     cualquier miembro sobre **sus propias** citas: marcar que el cliente
         *     llegó no es un acto administrativo, es el empleado haciendo su
         *     trabajo. Ver `CONTRATO.md` sección 5.6.
         *
         *     Listar devuelve solo las citas propias salvo que se tenga
         *     `puede_ver_agenda_completa`: cada cita trae nombre y teléfono del
         *     cliente, así que la agenda completa **es** la libreta de clientes del
         *     negocio (ver `CONTRATO.md` sección 5.8).
         */
        post: operations["agenda_citas_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agenda/citas/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Agenda: crear y consultar citas, y transicionar su estado.
         *
         *     Crear requiere `puede_gestionar_agenda`. `empleado` es opcional al
         *     crear: si se omite, el servicio de agenda asigna automáticamente el
         *     primer empleado disponible ("cualquiera disponible").
         *
         *     Transicionar (`confirmar`/`completar`/`cancelar`) lo puede hacer quien
         *     tenga `puede_gestionar_agenda` sobre **cualquier** cita del negocio, o
         *     cualquier miembro sobre **sus propias** citas: marcar que el cliente
         *     llegó no es un acto administrativo, es el empleado haciendo su
         *     trabajo. Ver `CONTRATO.md` sección 5.6.
         *
         *     Listar devuelve solo las citas propias salvo que se tenga
         *     `puede_ver_agenda_completa`: cada cita trae nombre y teléfono del
         *     cliente, así que la agenda completa **es** la libreta de clientes del
         *     negocio (ver `CONTRATO.md` sección 5.8).
         */
        get: operations["agenda_citas_retrieve"];
        /**
         * @description Agenda: crear y consultar citas, y transicionar su estado.
         *
         *     Crear requiere `puede_gestionar_agenda`. `empleado` es opcional al
         *     crear: si se omite, el servicio de agenda asigna automáticamente el
         *     primer empleado disponible ("cualquiera disponible").
         *
         *     Transicionar (`confirmar`/`completar`/`cancelar`) lo puede hacer quien
         *     tenga `puede_gestionar_agenda` sobre **cualquier** cita del negocio, o
         *     cualquier miembro sobre **sus propias** citas: marcar que el cliente
         *     llegó no es un acto administrativo, es el empleado haciendo su
         *     trabajo. Ver `CONTRATO.md` sección 5.6.
         *
         *     Listar devuelve solo las citas propias salvo que se tenga
         *     `puede_ver_agenda_completa`: cada cita trae nombre y teléfono del
         *     cliente, así que la agenda completa **es** la libreta de clientes del
         *     negocio (ver `CONTRATO.md` sección 5.8).
         */
        put: operations["agenda_citas_update"];
        post?: never;
        /**
         * @description Agenda: crear y consultar citas, y transicionar su estado.
         *
         *     Crear requiere `puede_gestionar_agenda`. `empleado` es opcional al
         *     crear: si se omite, el servicio de agenda asigna automáticamente el
         *     primer empleado disponible ("cualquiera disponible").
         *
         *     Transicionar (`confirmar`/`completar`/`cancelar`) lo puede hacer quien
         *     tenga `puede_gestionar_agenda` sobre **cualquier** cita del negocio, o
         *     cualquier miembro sobre **sus propias** citas: marcar que el cliente
         *     llegó no es un acto administrativo, es el empleado haciendo su
         *     trabajo. Ver `CONTRATO.md` sección 5.6.
         *
         *     Listar devuelve solo las citas propias salvo que se tenga
         *     `puede_ver_agenda_completa`: cada cita trae nombre y teléfono del
         *     cliente, así que la agenda completa **es** la libreta de clientes del
         *     negocio (ver `CONTRATO.md` sección 5.8).
         */
        delete: operations["agenda_citas_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Agenda: crear y consultar citas, y transicionar su estado.
         *
         *     Crear requiere `puede_gestionar_agenda`. `empleado` es opcional al
         *     crear: si se omite, el servicio de agenda asigna automáticamente el
         *     primer empleado disponible ("cualquiera disponible").
         *
         *     Transicionar (`confirmar`/`completar`/`cancelar`) lo puede hacer quien
         *     tenga `puede_gestionar_agenda` sobre **cualquier** cita del negocio, o
         *     cualquier miembro sobre **sus propias** citas: marcar que el cliente
         *     llegó no es un acto administrativo, es el empleado haciendo su
         *     trabajo. Ver `CONTRATO.md` sección 5.6.
         *
         *     Listar devuelve solo las citas propias salvo que se tenga
         *     `puede_ver_agenda_completa`: cada cita trae nombre y teléfono del
         *     cliente, así que la agenda completa **es** la libreta de clientes del
         *     negocio (ver `CONTRATO.md` sección 5.8).
         */
        patch: operations["agenda_citas_partial_update"];
        trace?: never;
    };
    "/api/agenda/citas/{id}/cancelar/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Agenda: crear y consultar citas, y transicionar su estado.
         *
         *     Crear requiere `puede_gestionar_agenda`. `empleado` es opcional al
         *     crear: si se omite, el servicio de agenda asigna automáticamente el
         *     primer empleado disponible ("cualquiera disponible").
         *
         *     Transicionar (`confirmar`/`completar`/`cancelar`) lo puede hacer quien
         *     tenga `puede_gestionar_agenda` sobre **cualquier** cita del negocio, o
         *     cualquier miembro sobre **sus propias** citas: marcar que el cliente
         *     llegó no es un acto administrativo, es el empleado haciendo su
         *     trabajo. Ver `CONTRATO.md` sección 5.6.
         *
         *     Listar devuelve solo las citas propias salvo que se tenga
         *     `puede_ver_agenda_completa`: cada cita trae nombre y teléfono del
         *     cliente, así que la agenda completa **es** la libreta de clientes del
         *     negocio (ver `CONTRATO.md` sección 5.8).
         */
        post: operations["agenda_citas_cancelar_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agenda/citas/{id}/completar/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Agenda: crear y consultar citas, y transicionar su estado.
         *
         *     Crear requiere `puede_gestionar_agenda`. `empleado` es opcional al
         *     crear: si se omite, el servicio de agenda asigna automáticamente el
         *     primer empleado disponible ("cualquiera disponible").
         *
         *     Transicionar (`confirmar`/`completar`/`cancelar`) lo puede hacer quien
         *     tenga `puede_gestionar_agenda` sobre **cualquier** cita del negocio, o
         *     cualquier miembro sobre **sus propias** citas: marcar que el cliente
         *     llegó no es un acto administrativo, es el empleado haciendo su
         *     trabajo. Ver `CONTRATO.md` sección 5.6.
         *
         *     Listar devuelve solo las citas propias salvo que se tenga
         *     `puede_ver_agenda_completa`: cada cita trae nombre y teléfono del
         *     cliente, así que la agenda completa **es** la libreta de clientes del
         *     negocio (ver `CONTRATO.md` sección 5.8).
         */
        post: operations["agenda_citas_completar_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agenda/citas/{id}/confirmar/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Agenda: crear y consultar citas, y transicionar su estado.
         *
         *     Crear requiere `puede_gestionar_agenda`. `empleado` es opcional al
         *     crear: si se omite, el servicio de agenda asigna automáticamente el
         *     primer empleado disponible ("cualquiera disponible").
         *
         *     Transicionar (`confirmar`/`completar`/`cancelar`) lo puede hacer quien
         *     tenga `puede_gestionar_agenda` sobre **cualquier** cita del negocio, o
         *     cualquier miembro sobre **sus propias** citas: marcar que el cliente
         *     llegó no es un acto administrativo, es el empleado haciendo su
         *     trabajo. Ver `CONTRATO.md` sección 5.6.
         *
         *     Listar devuelve solo las citas propias salvo que se tenga
         *     `puede_ver_agenda_completa`: cada cita trae nombre y teléfono del
         *     cliente, así que la agenda completa **es** la libreta de clientes del
         *     negocio (ver `CONTRATO.md` sección 5.8).
         */
        post: operations["agenda_citas_confirmar_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agenda/horario-negocio/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Horario de atención del negocio del usuario autenticado.
         *
         *     Es el horario que rige por defecto para todo el equipo: quien no tenga horario propio cargado trabaja este. Lo puede leer cualquier miembro.
         */
        get: operations["agenda_horario_negocio_list"];
        /**
         * @description Reemplaza el horario de atención del negocio en una sola transacción. Requiere `puede_configurar_horarios` — decidir cuándo abre el local es una decisión distinta de operar la agenda del día.
         *
         *     Cambiarlo acá cambia la disponibilidad de **todos** los empleados que lo heredan, que es el caso normal. Los que tienen horario propio (ver `PUT /api/agenda/horarios/semana/`) no se ven afectados.
         *
         *     Semántica de **reemplazo**: las franjas enviadas pasan a ser el horario completo; lo que no venga se borra. Enviar `franjas: []` deja al negocio sin horario, y entonces nadie que herede tiene disponibilidad.
         */
        put: operations["agenda_horario_negocio_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agenda/horarios/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Horario propio de un empleado, como excepción al del negocio.
         *
         *     Escribir requiere `puede_configurar_horarios`, no
         *     `puede_gestionar_agenda`: decidir cuándo trabaja alguien es una
         *     decisión distinta de operar la agenda del día (ver `CONTRATO.md`
         *     sección 5.8).
         */
        get: operations["agenda_horarios_list"];
        put?: never;
        /**
         * @description Horario propio de un empleado, como excepción al del negocio.
         *
         *     Escribir requiere `puede_configurar_horarios`, no
         *     `puede_gestionar_agenda`: decidir cuándo trabaja alguien es una
         *     decisión distinta de operar la agenda del día (ver `CONTRATO.md`
         *     sección 5.8).
         */
        post: operations["agenda_horarios_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agenda/horarios/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Horario propio de un empleado, como excepción al del negocio.
         *
         *     Escribir requiere `puede_configurar_horarios`, no
         *     `puede_gestionar_agenda`: decidir cuándo trabaja alguien es una
         *     decisión distinta de operar la agenda del día (ver `CONTRATO.md`
         *     sección 5.8).
         */
        get: operations["agenda_horarios_retrieve"];
        /**
         * @description Horario propio de un empleado, como excepción al del negocio.
         *
         *     Escribir requiere `puede_configurar_horarios`, no
         *     `puede_gestionar_agenda`: decidir cuándo trabaja alguien es una
         *     decisión distinta de operar la agenda del día (ver `CONTRATO.md`
         *     sección 5.8).
         */
        put: operations["agenda_horarios_update"];
        post?: never;
        /**
         * @description Horario propio de un empleado, como excepción al del negocio.
         *
         *     Escribir requiere `puede_configurar_horarios`, no
         *     `puede_gestionar_agenda`: decidir cuándo trabaja alguien es una
         *     decisión distinta de operar la agenda del día (ver `CONTRATO.md`
         *     sección 5.8).
         */
        delete: operations["agenda_horarios_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Horario propio de un empleado, como excepción al del negocio.
         *
         *     Escribir requiere `puede_configurar_horarios`, no
         *     `puede_gestionar_agenda`: decidir cuándo trabaja alguien es una
         *     decisión distinta de operar la agenda del día (ver `CONTRATO.md`
         *     sección 5.8).
         */
        patch: operations["agenda_horarios_partial_update"];
        trace?: never;
    };
    "/api/agenda/horarios/semana/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * @description Reemplaza el horario **propio** de uno o varios empleados, en una sola transacción.
         *
         *     El horario propio es la **excepción** al horario del negocio (ver `PUT /api/agenda/horario-negocio/`), para quien no trabaja como el resto: medio tiempo, solo sábados, turno de tarde. Si un empleado no tiene horario propio, hereda el del negocio — que es el caso normal y no requiere llamar a este endpoint.
         *
         *     `miembros` es una lista porque los de medio tiempo suelen compartir turno. Un solo empleado es el caso `miembros: [id]`.
         *
         *     Semántica de **reemplazo**: las franjas enviadas pasan a ser el horario propio completo de **cada** empleado señalado. Enviar `franjas: []` le quita el horario propio y lo devuelve a heredar el del negocio; para que alguien no atienda, la palanca es `activo=False` en su membresía, no un horario vacío.
         *
         *     Todo o nada: si la semana es inválida, o si alguno de los `miembros` no pertenece al negocio, responde `400` y no se toca el horario de nadie.
         */
        put: operations["agenda_horarios_semana_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/negocios/cargos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Los cargos que define **este** negocio.
         *
         *     No hay catálogo global: cada negocio nace con tres cargos de arranque
         *     (`sembrar_cargos_iniciales`) y desde ahí los renombra, los edita, crea
         *     otros o borra los que no usa.
         *
         *     Leer solo requiere pertenecer al negocio —la UI necesita mostrar en
         *     qué cargo está cada quien— pero escribir exige
         *     `puede_gestionar_empleados`, igual que tocar a un empleado: definir lo
         *     que puede hacer un cargo **es** dar permisos.
         */
        get: operations["negocios_cargos_list"];
        put?: never;
        /**
         * @description Los cargos que define **este** negocio.
         *
         *     No hay catálogo global: cada negocio nace con tres cargos de arranque
         *     (`sembrar_cargos_iniciales`) y desde ahí los renombra, los edita, crea
         *     otros o borra los que no usa.
         *
         *     Leer solo requiere pertenecer al negocio —la UI necesita mostrar en
         *     qué cargo está cada quien— pero escribir exige
         *     `puede_gestionar_empleados`, igual que tocar a un empleado: definir lo
         *     que puede hacer un cargo **es** dar permisos.
         */
        post: operations["negocios_cargos_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/negocios/cargos/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Los cargos que define **este** negocio.
         *
         *     No hay catálogo global: cada negocio nace con tres cargos de arranque
         *     (`sembrar_cargos_iniciales`) y desde ahí los renombra, los edita, crea
         *     otros o borra los que no usa.
         *
         *     Leer solo requiere pertenecer al negocio —la UI necesita mostrar en
         *     qué cargo está cada quien— pero escribir exige
         *     `puede_gestionar_empleados`, igual que tocar a un empleado: definir lo
         *     que puede hacer un cargo **es** dar permisos.
         */
        get: operations["negocios_cargos_retrieve"];
        /**
         * @description Los cargos que define **este** negocio.
         *
         *     No hay catálogo global: cada negocio nace con tres cargos de arranque
         *     (`sembrar_cargos_iniciales`) y desde ahí los renombra, los edita, crea
         *     otros o borra los que no usa.
         *
         *     Leer solo requiere pertenecer al negocio —la UI necesita mostrar en
         *     qué cargo está cada quien— pero escribir exige
         *     `puede_gestionar_empleados`, igual que tocar a un empleado: definir lo
         *     que puede hacer un cargo **es** dar permisos.
         */
        put: operations["negocios_cargos_update"];
        post?: never;
        /**
         * @description Los cargos que define **este** negocio.
         *
         *     No hay catálogo global: cada negocio nace con tres cargos de arranque
         *     (`sembrar_cargos_iniciales`) y desde ahí los renombra, los edita, crea
         *     otros o borra los que no usa.
         *
         *     Leer solo requiere pertenecer al negocio —la UI necesita mostrar en
         *     qué cargo está cada quien— pero escribir exige
         *     `puede_gestionar_empleados`, igual que tocar a un empleado: definir lo
         *     que puede hacer un cargo **es** dar permisos.
         */
        delete: operations["negocios_cargos_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Los cargos que define **este** negocio.
         *
         *     No hay catálogo global: cada negocio nace con tres cargos de arranque
         *     (`sembrar_cargos_iniciales`) y desde ahí los renombra, los edita, crea
         *     otros o borra los que no usa.
         *
         *     Leer solo requiere pertenecer al negocio —la UI necesita mostrar en
         *     qué cargo está cada quien— pero escribir exige
         *     `puede_gestionar_empleados`, igual que tocar a un empleado: definir lo
         *     que puede hacer un cargo **es** dar permisos.
         */
        patch: operations["negocios_cargos_partial_update"];
        trace?: never;
    };
    "/api/negocios/empleados/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Lista o agrega empleados del negocio del usuario autenticado.
         *
         *     Endpoint de **gestión**: expone email y capacidades de cada miembro,
         *     así que exige `puede_gestionar_empleados` también para listar, no
         *     solo para crear. Quien solo necesita saber quiénes son sus
         *     compañeros (la agenda) usa `GET /api/negocios/equipo/`, que
         *     devuelve una vista mínima sin datos personales.
         *
         *     El queryset se filtra siempre por el negocio de la membresía activa
         *     del solicitante: nunca se exponen empleados de otro tenant.
         */
        get: operations["negocios_empleados_list"];
        put?: never;
        /**
         * @description Lista o agrega empleados del negocio del usuario autenticado.
         *
         *     Endpoint de **gestión**: expone email y capacidades de cada miembro,
         *     así que exige `puede_gestionar_empleados` también para listar, no
         *     solo para crear. Quien solo necesita saber quiénes son sus
         *     compañeros (la agenda) usa `GET /api/negocios/equipo/`, que
         *     devuelve una vista mínima sin datos personales.
         *
         *     El queryset se filtra siempre por el negocio de la membresía activa
         *     del solicitante: nunca se exponen empleados de otro tenant.
         */
        post: operations["negocios_empleados_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/negocios/empleados/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Detalle y edición de un empleado puntual del negocio.
         *
         *     Tanto ver como editar requieren `puede_gestionar_empleados`: el
         *     detalle incluye email y capacidades, que son datos de gestión. Nunca
         *     expone empleados de otro tenant: el queryset ya viene acotado al
         *     negocio de la membresía del solicitante.
         */
        get: operations["negocios_empleados_retrieve"];
        /**
         * @description Detalle y edición de un empleado puntual del negocio.
         *
         *     Tanto ver como editar requieren `puede_gestionar_empleados`: el
         *     detalle incluye email y capacidades, que son datos de gestión. Nunca
         *     expone empleados de otro tenant: el queryset ya viene acotado al
         *     negocio de la membresía del solicitante.
         */
        put: operations["negocios_empleados_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description Detalle y edición de un empleado puntual del negocio.
         *
         *     Tanto ver como editar requieren `puede_gestionar_empleados`: el
         *     detalle incluye email y capacidades, que son datos de gestión. Nunca
         *     expone empleados de otro tenant: el queryset ya viene acotado al
         *     negocio de la membresía del solicitante.
         */
        patch: operations["negocios_empleados_partial_update"];
        trace?: never;
    };
    "/api/negocios/equipo/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Directorio mínimo del equipo, para cualquier miembro del negocio.
         *
         *     Devuelve solo `id`, `nombre`, `especialidad` y `activo`: lo que la
         *     agenda necesita para filtrar el calendario, ofrecer "cualquiera
         *     disponible" y cargar horarios, sin exponer email ni capacidades.
         *
         *     Separado de `/empleados/` a propósito: así cada endpoint tiene una
         *     forma honesta en el schema, en vez de un mismo endpoint que devuelve
         *     más o menos campos según quién pregunte.
         */
        get: operations["negocios_equipo_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/negocios/mi-membresia/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Quién soy, en qué negocio y qué puedo hacer.
         *
         *     Pensado para que el frontend lo llame justo después de loguearse
         *     (o al recuperar sesión desde tokens guardados) y resuelva de una
         *     sola vez sus propias capacidades + los datos del negocio, sin
         *     tener que listar empleados y buscarse a sí mismo por email.
         */
        get: operations["negocios_mi_membresia_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/negocios/registro/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Alta de un negocio nuevo, sus cargos de arranque y su dueño.
         *
         *     El negocio nace con tres cargos editables (Administración, Recepción,
         *     Barbero o estilista) y el dueño entra en el de Administración. Los
         *     empleados que vengan en el mismo request entran al cargo operativo;
         *     cambiarles el cargo es un paso posterior ya autenticado.
         */
        post: operations["negocios_registro_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servicios/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description CRUD de servicios del negocio del usuario autenticado.
         *
         *     Leer requiere solo pertenecer al negocio; crear/editar/borrar
         *     requiere la capacidad `puede_editar_precios`, porque un servicio
         *     define precio y comisión.
         */
        get: operations["servicios_list"];
        put?: never;
        /**
         * @description CRUD de servicios del negocio del usuario autenticado.
         *
         *     Leer requiere solo pertenecer al negocio; crear/editar/borrar
         *     requiere la capacidad `puede_editar_precios`, porque un servicio
         *     define precio y comisión.
         */
        post: operations["servicios_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servicios/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description CRUD de servicios del negocio del usuario autenticado.
         *
         *     Leer requiere solo pertenecer al negocio; crear/editar/borrar
         *     requiere la capacidad `puede_editar_precios`, porque un servicio
         *     define precio y comisión.
         */
        get: operations["servicios_retrieve"];
        /**
         * @description CRUD de servicios del negocio del usuario autenticado.
         *
         *     Leer requiere solo pertenecer al negocio; crear/editar/borrar
         *     requiere la capacidad `puede_editar_precios`, porque un servicio
         *     define precio y comisión.
         */
        put: operations["servicios_update"];
        post?: never;
        /**
         * @description CRUD de servicios del negocio del usuario autenticado.
         *
         *     Leer requiere solo pertenecer al negocio; crear/editar/borrar
         *     requiere la capacidad `puede_editar_precios`, porque un servicio
         *     define precio y comisión.
         */
        delete: operations["servicios_destroy"];
        options?: never;
        head?: never;
        /**
         * @description CRUD de servicios del negocio del usuario autenticado.
         *
         *     Leer requiere solo pertenecer al negocio; crear/editar/borrar
         *     requiere la capacidad `puede_editar_precios`, porque un servicio
         *     define precio y comisión.
         */
        patch: operations["servicios_partial_update"];
        trace?: never;
    };
    "/api/servicios/lote/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Crea varios servicios en una sola transacción: entran todos o ninguno.
         *
         *     Pensado para el alta desde catálogo del frontend, que antes emitía un POST por servicio y podía quedar a medias si fallaba la red.
         */
        post: operations["servicios_lote_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Un cargo del negocio: nombre, tipo y qué concede.
         *
         *     `miembros` sirve para que la UI avise antes de borrar y para explicar
         *     a cuánta gente afecta editarlo — que es la contrapartida de que el
         *     cargo sea la única fuente de verdad.
         */
        Cargo: {
            readonly id: number;
            nombre: string;
            tipo?: components["schemas"]["TipoEnum"];
            readonly miembros: number;
            puede_cobrar?: boolean;
            puede_ver_reportes?: boolean;
            puede_editar_precios?: boolean;
            puede_gestionar_empleados?: boolean;
            puede_gestionar_agenda?: boolean;
            puede_configurar_horarios?: boolean;
            puede_ver_agenda_completa?: boolean;
        };
        Cita: {
            readonly id: number;
            servicio: number;
            readonly servicio_nombre: string;
            empleado: number;
            readonly empleado_nombre: string;
            /** Format: date-time */
            fecha_hora_inicio: string;
            /** Format: date-time */
            readonly fecha_hora_fin: string;
            readonly estado: components["schemas"]["EstadoEnum"];
            nombre_cliente: string;
            telefono_cliente?: string;
            notas?: string;
        };
        /**
         * @description Entrada para agendar una cita. `empleado` es opcional: si se
         *     omite, se asigna automáticamente el primer empleado disponible.
         */
        CitaCreate: {
            servicio: number;
            empleado?: number | null;
            /** Format: date-time */
            fecha_hora_inicio: string;
            nombre_cliente: string;
            /** @default  */
            telefono_cliente: string;
            /** @default  */
            notas: string;
        };
        /**
         * @description * `0` - Lunes
         *     * `1` - Martes
         *     * `2` - Miércoles
         *     * `3` - Jueves
         *     * `4` - Viernes
         *     * `5` - Sábado
         *     * `6` - Domingo
         * @enum {integer}
         */
        DiaSemanaEnum: 0 | 1 | 2 | 3 | 4 | 5 | 6;
        /** @description Empleado adicional: sus datos de acceso y en qué cargo entra. */
        EmpleadoAlta: {
            /** Format: email */
            email: string;
            nombre: string;
            password: string;
            /** @default  */
            especialidad: string;
            cargo?: number | null;
        };
        /**
         * @description Empleado dado de alta **dentro del registro del negocio**.
         *
         *     Sin `cargo` a propósito: en ese request los cargos del negocio todavía
         *     no existen, así que un id solo podría apuntar a otro negocio. Estos
         *     empleados entran al cargo operativo sembrado y el dueño les cambia el
         *     cargo después, ya autenticado.
         */
        EmpleadoAltaRegistro: {
            /** Format: email */
            email: string;
            nombre: string;
            password: string;
            /** @default  */
            especialidad: string;
        };
        /**
         * @description * `agendada` - Agendada
         *     * `confirmada` - Confirmada
         *     * `completada` - Completada
         *     * `cancelada` - Cancelada
         * @enum {string}
         */
        EstadoEnum: "agendada" | "confirmada" | "completada" | "cancelada";
        /**
         * @description Una franja suelta dentro de la semana. Sin `miembro`: lo define el
         *     contenedor, para no repetirlo en cada elemento de la lista.
         */
        FranjaHorario: {
            dia_semana: components["schemas"]["DiaSemanaEnum"];
            /** Format: time */
            hora_inicio: string;
            /** Format: time */
            hora_fin: string;
        };
        HorarioNegocio: {
            readonly id: number;
            dia_semana: components["schemas"]["DiaSemanaEnum"];
            /** Format: time */
            hora_inicio: string;
            /** Format: time */
            hora_fin: string;
        };
        /**
         * @description Entrada de `PUT /api/agenda/horario-negocio/`.
         *
         *     Solo `franjas`: el negocio sale del token, nunca del body (ver
         *     CONTRATO.md sección 5.5). Semántica de reemplazo, igual que el horario
         *     por empleado.
         */
        HorarioNegocioSemanal: {
            franjas: components["schemas"]["FranjaHorario"][];
        };
        /**
         * @description Entrada de `PUT /api/agenda/horarios/semana/`.
         *
         *     `miembros` es una lista porque lo normal es que todo el equipo comparta
         *     el mismo horario; un solo empleado es el caso n=1, no una forma aparte.
         *     Va vacía nunca: sin destinatarios no hay nada que aplicar.
         *
         *     Semántica de reemplazo: la lista de franjas es el horario completo de
         *     **cada** empleado señalado, no un agregado. Mandar `franjas: []` los
         *     deja sin disponibilidad.
         */
        HorarioSemanal: {
            miembros: number[];
            franjas: components["schemas"]["FranjaHorario"][];
        };
        HorarioTrabajo: {
            readonly id: number;
            miembro: number;
            dia_semana: components["schemas"]["DiaSemanaEnum"];
            /** Format: time */
            hora_inicio: string;
            /** Format: time */
            hora_fin: string;
        };
        /**
         * @description Forma de la respuesta de GET /api/negocios/mi-membresia/.
         *
         *     Resuelve de un solo request "quién soy, en qué negocio, **qué
         *     experiencia de la app me toca** y qué puedo hacer":
         *
         *     - `tipo` es el **discriminador de dominio** (viene del cargo). El
         *       frontend lo usa para decidir qué shell montar —qué navegación, qué
         *       pantalla inicial— sin encadenar condicionales por capacidad.
         *     - `cargo` trae el detalle con las capacidades, que es lo que gatea
         *       cada acción concreta dentro de ese shell.
         *
         *     Los dos niveles son a propósito (ver `CONTRATO.md` 5.10): el tipo
         *     decide la forma de la app, las capacidades deciden los botones. Y
         *     ninguno de los dos es la barrera de seguridad — el backend exige la
         *     capacidad en cada endpoint.
         */
        MiMembresia: {
            readonly id: number;
            /** Format: email */
            readonly email: string;
            readonly nombre: string;
            readonly especialidad: string;
            readonly negocio: components["schemas"]["Negocio"];
            readonly tipo: components["schemas"]["TipoEnum"];
            readonly cargo: components["schemas"]["Cargo"];
            readonly activo: boolean;
        };
        /**
         * @description Vista mínima de un compañero de trabajo, para quien NO gestiona
         *     el equipo.
         *
         *     Existe porque la agenda necesita listar empleados (filtrar el
         *     calendario, elegir a quién asignar una cita, cargar horarios), pero
         *     eso no justifica exponerle a cualquier miembro el email y la matriz
         *     de capacidades de todos sus compañeros — que es lo que hacía
         *     `MiembroNegocioSerializer` cuando se usaba para listar sin exigir
         *     `puede_gestionar_empleados`.
         *
         *     Deliberadamente sin `email` ni flags `puede_*`.
         */
        MiembroEquipo: {
            readonly id: number;
            readonly nombre: string;
            readonly especialidad: string;
            readonly activo: boolean;
        };
        /**
         * @description Un miembro visto desde la gestión del equipo.
         *
         *     Ya no lleva flags `puede_*`: las capacidades viven en el cargo. Se
         *     envía `cargo` (el id, que es lo editable) y `cargo_detalle` anidado
         *     para que la UI muestre el nombre y lo que concede sin un segundo
         *     request.
         */
        MiembroNegocio: {
            readonly id: number;
            /** Format: email */
            readonly email: string;
            readonly nombre: string;
            especialidad?: string;
            cargo?: number | null;
            readonly cargo_detalle: components["schemas"]["Cargo"];
            activo?: boolean;
        };
        Negocio: {
            readonly id: number;
            readonly nombre: string;
            readonly slug: string;
            readonly ciudad: string;
            readonly direccion: string;
            readonly telefono: string;
            readonly activo: boolean;
        };
        /**
         * @description Un cargo del negocio: nombre, tipo y qué concede.
         *
         *     `miembros` sirve para que la UI avise antes de borrar y para explicar
         *     a cuánta gente afecta editarlo — que es la contrapartida de que el
         *     cargo sea la única fuente de verdad.
         */
        PatchedCargo: {
            readonly id?: number;
            nombre?: string;
            tipo?: components["schemas"]["TipoEnum"];
            readonly miembros?: number;
            puede_cobrar?: boolean;
            puede_ver_reportes?: boolean;
            puede_editar_precios?: boolean;
            puede_gestionar_empleados?: boolean;
            puede_gestionar_agenda?: boolean;
            puede_configurar_horarios?: boolean;
            puede_ver_agenda_completa?: boolean;
        };
        PatchedCita: {
            readonly id?: number;
            servicio?: number;
            readonly servicio_nombre?: string;
            empleado?: number;
            readonly empleado_nombre?: string;
            /** Format: date-time */
            fecha_hora_inicio?: string;
            /** Format: date-time */
            readonly fecha_hora_fin?: string;
            readonly estado?: components["schemas"]["EstadoEnum"];
            nombre_cliente?: string;
            telefono_cliente?: string;
            notas?: string;
        };
        PatchedHorarioTrabajo: {
            readonly id?: number;
            miembro?: number;
            dia_semana?: components["schemas"]["DiaSemanaEnum"];
            /** Format: time */
            hora_inicio?: string;
            /** Format: time */
            hora_fin?: string;
        };
        /**
         * @description Un miembro visto desde la gestión del equipo.
         *
         *     Ya no lleva flags `puede_*`: las capacidades viven en el cargo. Se
         *     envía `cargo` (el id, que es lo editable) y `cargo_detalle` anidado
         *     para que la UI muestre el nombre y lo que concede sin un segundo
         *     request.
         */
        PatchedMiembroNegocio: {
            readonly id?: number;
            /** Format: email */
            readonly email?: string;
            readonly nombre?: string;
            especialidad?: string;
            cargo?: number | null;
            readonly cargo_detalle?: components["schemas"]["Cargo"];
            activo?: boolean;
        };
        PatchedServicio: {
            readonly id?: number;
            nombre?: string;
            descripcion?: string;
            categoria?: string;
            /** Format: decimal */
            precio?: string;
            duracion_minutos?: number;
            /** Format: decimal */
            porcentaje_comision?: string;
            activo?: boolean;
        };
        RegistroNegocio: {
            nombre_negocio: string;
            ciudad?: string;
            direccion?: string;
            telefono?: string;
            /** Format: email */
            email_dueno: string;
            nombre_dueno: string;
            password_dueno: string;
            empleados?: components["schemas"]["EmpleadoAltaRegistro"][];
        };
        /** @description Forma de la respuesta de POST /api/negocios/registro/. */
        RegistroNegocioRespuesta: {
            negocio: components["schemas"]["Negocio"];
            access: string;
            refresh: string;
        };
        Servicio: {
            readonly id: number;
            nombre: string;
            descripcion?: string;
            categoria?: string;
            /** Format: decimal */
            precio: string;
            duracion_minutos: number;
            /** Format: decimal */
            porcentaje_comision?: string;
            activo?: boolean;
        };
        /**
         * @description Entrada de `POST /api/servicios/lote/`.
         *
         *     Se creó como endpoint aparte en vez de aceptar una lista en el `POST`
         *     normal para no volver ambiguo el body de creación de a uno: el
         *     schema OpenAPI quedaría con un `oneOf` que el frontend tendría que
         *     desambiguar en cada llamada.
         */
        ServicioLote: {
            servicios: components["schemas"]["Servicio"][];
        };
        /**
         * @description * `administracion` - Administración
         *     * `recepcion` - Recepción
         *     * `operativo` - Operativo
         * @enum {string}
         */
        TipoEnum: "administracion" | "recepcion" | "operativo";
        TokenObtainPair: {
            email: string;
            password: string;
            readonly access: string;
            readonly refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    agenda_citas_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cita"][];
                };
            };
        };
    };
    agenda_citas_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CitaCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["CitaCreate"];
                "multipart/form-data": components["schemas"]["CitaCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cita"];
                };
            };
        };
    };
    agenda_citas_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this cita. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cita"];
                };
            };
        };
    };
    agenda_citas_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this cita. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Cita"];
                "application/x-www-form-urlencoded": components["schemas"]["Cita"];
                "multipart/form-data": components["schemas"]["Cita"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cita"];
                };
            };
        };
    };
    agenda_citas_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this cita. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    agenda_citas_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this cita. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCita"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCita"];
                "multipart/form-data": components["schemas"]["PatchedCita"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cita"];
                };
            };
        };
    };
    agenda_citas_cancelar_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this cita. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cita"];
                };
            };
        };
    };
    agenda_citas_completar_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this cita. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cita"];
                };
            };
        };
    };
    agenda_citas_confirmar_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this cita. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cita"];
                };
            };
        };
    };
    agenda_horario_negocio_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HorarioNegocio"][];
                };
            };
        };
    };
    agenda_horario_negocio_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HorarioNegocioSemanal"];
                "application/x-www-form-urlencoded": components["schemas"]["HorarioNegocioSemanal"];
                "multipart/form-data": components["schemas"]["HorarioNegocioSemanal"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HorarioNegocio"][];
                };
            };
        };
    };
    agenda_horarios_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HorarioTrabajo"][];
                };
            };
        };
    };
    agenda_horarios_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HorarioTrabajo"];
                "application/x-www-form-urlencoded": components["schemas"]["HorarioTrabajo"];
                "multipart/form-data": components["schemas"]["HorarioTrabajo"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HorarioTrabajo"];
                };
            };
        };
    };
    agenda_horarios_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this horario trabajo. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HorarioTrabajo"];
                };
            };
        };
    };
    agenda_horarios_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this horario trabajo. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HorarioTrabajo"];
                "application/x-www-form-urlencoded": components["schemas"]["HorarioTrabajo"];
                "multipart/form-data": components["schemas"]["HorarioTrabajo"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HorarioTrabajo"];
                };
            };
        };
    };
    agenda_horarios_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this horario trabajo. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    agenda_horarios_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this horario trabajo. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedHorarioTrabajo"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedHorarioTrabajo"];
                "multipart/form-data": components["schemas"]["PatchedHorarioTrabajo"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HorarioTrabajo"];
                };
            };
        };
    };
    agenda_horarios_semana_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HorarioSemanal"];
                "application/x-www-form-urlencoded": components["schemas"]["HorarioSemanal"];
                "multipart/form-data": components["schemas"]["HorarioSemanal"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HorarioTrabajo"][];
                };
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
                "multipart/form-data": components["schemas"]["TokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    negocios_cargos_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cargo"][];
                };
            };
        };
    };
    negocios_cargos_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Cargo"];
                "application/x-www-form-urlencoded": components["schemas"]["Cargo"];
                "multipart/form-data": components["schemas"]["Cargo"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cargo"];
                };
            };
        };
    };
    negocios_cargos_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this cargo. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cargo"];
                };
            };
        };
    };
    negocios_cargos_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this cargo. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Cargo"];
                "application/x-www-form-urlencoded": components["schemas"]["Cargo"];
                "multipart/form-data": components["schemas"]["Cargo"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cargo"];
                };
            };
        };
    };
    negocios_cargos_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this cargo. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    negocios_cargos_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this cargo. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCargo"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCargo"];
                "multipart/form-data": components["schemas"]["PatchedCargo"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cargo"];
                };
            };
        };
    };
    negocios_empleados_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MiembroNegocio"][];
                };
            };
        };
    };
    negocios_empleados_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmpleadoAlta"];
                "application/x-www-form-urlencoded": components["schemas"]["EmpleadoAlta"];
                "multipart/form-data": components["schemas"]["EmpleadoAlta"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MiembroNegocio"];
                };
            };
        };
    };
    negocios_empleados_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MiembroNegocio"];
                };
            };
        };
    };
    negocios_empleados_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MiembroNegocio"];
                "application/x-www-form-urlencoded": components["schemas"]["MiembroNegocio"];
                "multipart/form-data": components["schemas"]["MiembroNegocio"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MiembroNegocio"];
                };
            };
        };
    };
    negocios_empleados_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMiembroNegocio"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedMiembroNegocio"];
                "multipart/form-data": components["schemas"]["PatchedMiembroNegocio"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MiembroNegocio"];
                };
            };
        };
    };
    negocios_equipo_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MiembroEquipo"][];
                };
            };
        };
    };
    negocios_mi_membresia_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MiMembresia"];
                };
            };
        };
    };
    negocios_registro_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistroNegocio"];
                "application/x-www-form-urlencoded": components["schemas"]["RegistroNegocio"];
                "multipart/form-data": components["schemas"]["RegistroNegocio"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistroNegocioRespuesta"];
                };
            };
        };
    };
    servicios_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Servicio"][];
                };
            };
        };
    };
    servicios_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Servicio"];
                "application/x-www-form-urlencoded": components["schemas"]["Servicio"];
                "multipart/form-data": components["schemas"]["Servicio"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Servicio"];
                };
            };
        };
    };
    servicios_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this servicio. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Servicio"];
                };
            };
        };
    };
    servicios_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this servicio. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Servicio"];
                "application/x-www-form-urlencoded": components["schemas"]["Servicio"];
                "multipart/form-data": components["schemas"]["Servicio"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Servicio"];
                };
            };
        };
    };
    servicios_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this servicio. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    servicios_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this servicio. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedServicio"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedServicio"];
                "multipart/form-data": components["schemas"]["PatchedServicio"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Servicio"];
                };
            };
        };
    };
    servicios_lote_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServicioLote"];
                "application/x-www-form-urlencoded": components["schemas"]["ServicioLote"];
                "multipart/form-data": components["schemas"]["ServicioLote"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Servicio"][];
                };
            };
        };
    };
}
