# Generated by Django 5.0.6 on 2026-07-28 18:28

import apps.negocios.models
import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0002_negocio_logo_fotonegocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='color_acento',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Usa un color en formato #rrggbb, por ejemplo #10b981.', regex=re.compile('^#(?:[0-9a-fA-F]{6})$'))]),
        ),
        migrations.AddField(
            model_name='negocio',
            name='portada',
            field=models.ImageField(blank=True, upload_to=apps.negocios.models.ruta_portada),
        ),
        migrations.AddField(
            model_name='negocio',
            name='tema',
            field=models.CharField(choices=[('estandar', 'Estándar'), ('vitrina', 'Vitrina')], default='estandar', max_length=20),
        ),
    ]
