# Generated by Django 5.0.6 on 2026-07-29 03:18

import django.db.models.deletion
from django.db import migrations, models


def ruta_evidencia(instancia, nombre_archivo):
    """Copia local del `upload_to` que vivía en `apps.servicios.models`.

    `RegistroServicio` se eliminó en la migración 0003 (rediseño del
    módulo de dinero, 2026-08-07) y su modelo se fue con él. Una
    migración histórica no puede depender de código que ya no existe: sin
    esta copia, `makemigrations` revienta al cargar el grafo. Nunca se
    ejecuta — para cuando esta migración corre, el modelo se crea y tres
    migraciones después se borra, sin que nadie suba un archivo.
    """
    return nombre_archivo


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0004_plantillas_por_rubro'),
        ('servicios', '0001_initial'),
        ('tenants', '0001_initial'),
        ('usuarios', '0006_cargo_puede_aprobar_servicios'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=150)),
                ('telefono_cliente', models.CharField(blank=True, max_length=30)),
                ('fecha_hora', models.DateTimeField(help_text='Cuándo ocurrió el servicio. No puede ser futura.')),
                ('observaciones', models.TextField(blank=True)),
                ('evidencia', models.ImageField(blank=True, upload_to=ruta_evidencia)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_revisados', to='usuarios.miembronegocio')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_servicio', to='usuarios.miembronegocio')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_servicio', to='negocios.negocio')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='servicios.servicio')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
