# Generated by Django 5.0.6 on 2026-07-29 03:18

import apps.servicios.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0004_plantillas_por_rubro'),
        ('servicios', '0001_initial'),
        ('tenants', '0001_initial'),
        ('usuarios', '0006_cargo_puede_aprobar_servicios'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=150)),
                ('telefono_cliente', models.CharField(blank=True, max_length=30)),
                ('fecha_hora', models.DateTimeField(help_text='Cuándo ocurrió el servicio. No puede ser futura.')),
                ('observaciones', models.TextField(blank=True)),
                ('evidencia', models.ImageField(blank=True, upload_to=apps.servicios.models.ruta_evidencia)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_revisados', to='usuarios.miembronegocio')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_servicio', to='usuarios.miembronegocio')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_servicio', to='negocios.negocio')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='servicios.servicio')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
