# Generated by Django 5.0.6 on 2026-08-07 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_comisiondevengada_devolucion_pago_venta_ventaitem_and_more'),
        ('servicios', '0002_registroservicio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroServicio',
        ),
    ]
